# Generated by Django 5.1.5 on 2025-02-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gps',
            field=models.CharField(default='Sin GPS', max_length=100, verbose_name='GPS'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='AtractivosTuristicos_article',
        ),
    ]
