# Generated by Django 5.1.5 on 2025-02-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0003_article_gps_alter_article_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ascensor',
            table='AtractivosTuristicos_ascensor',
        ),
    ]
