# Generated by Django 5.1.5 on 2025-02-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0004_alter_ascensor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iglesia',
            table='AtractivosTuristicos_iglesia',
        ),
    ]
