# Generated by Django 5.1.6 on 2025-02-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0006_alter_arquitectura_table_alter_escalera_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='place',
        ),
    ]
