# Generated by Django 5.1.6 on 2025-02-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0007_rename_title_article_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='StreetArt',
        ),
    ]
