# Generated by Django 5.1.6 on 2025-02-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0008_auto_20250218_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streetart',
            old_name='content',
            new_name='direccion',
        ),
    ]
