# Generated by Django 5.1.6 on 2025-02-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0009_auto_20250218_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquitectura',
            old_name='descripcion',
            new_name='content',
        ),
    ]
