# Generated by Django 5.1.6 on 2025-02-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0011_auto_20250218_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name = 'arquitectura',
            old_name = 'lugar',
            new_name = 'place',
        ),
        migrations.RenameField(
            model_name = 'arquitectura',
            old_name = 'content',
            new_name = 'nombre',
        ),
            migrations.RenameField(
            model_name = 'arquitectura',
            old_name = 'antecedentes',
            new_name = 'content',
        ),
    ]
