# Generated by Django 5.1.6 on 2025-02-19 15:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0014_alter_arquitectura_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquitectura',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Sin contenido'),
        ),
    ]
