# Generated by Django 5.1.6 on 2025-02-19 16:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0015_arquitectura_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquitectura',
            name='contenido',
        ),
        migrations.AlterField(
            model_name='arquitectura',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
