# Generated by Django 5.1.6 on 2025-02-19 17:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0017_auto_20250219_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iglesia',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='iglesia',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Sin contenido'),
        ),
    ]
