# Generated by Django 5.1.6 on 2025-02-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtractivosTuristicos', '0018_remove_iglesia_descripcion_iglesia_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name = 'iglesia',
            old_name = 'lugar',
            new_name = 'place',
        ),
    ]
